DROP TABLE Categorie CASCADE;

DROP TABLE Pays CASCADE;

DROP TABLE Ville CASCADE;

DROP TABLE Client CASCADE;

DROP TABLE Usine CASCADE;

DROP TABLE Marque CASCADE;

DROP TABLE Modele CASCADE;

DROP TABLE Produit CASCADE;

DROP TABLE Fabrication CASCADE;

DROP TABLE Magasin CASCADE;

DROP TABLE PaysHabitant CASCADE;

DROP TABLE Vente CASCADE;

DROP TABLE VenteProduit CASCADE;